
spring:
  profiles: 
    active: dev

---
server: 
  port: 7001

spring: 
  profiles: dev     #开发环境
  application: 
    name: tensquare-eureka-server

eureka:
  instance:
    hostname: localhost   #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localhost:7001/eureka/
      #设置为另外两个节点的IP

---
server: 
  port: 7001

spring: 
  profiles: test     #测试环境
  application: 
    name: tensquare-eureka-server

eureka:
  instance:
    hostname: localhost   #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置为另外两个节点的IP 
